services:

  postgres:
    image: 'postgres:latest'
    container_name: crm_db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
  crm:
    build: .
    container_name: crm_app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis