services:
  postgres:
    image: 'postgres:latest'
    container_name: crm_db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'